import Head from "next/head";
import Header from "../components/Header";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HoverCard from "../components/HoverCard";

export default function Home() {
  return (
    <div className="bg-black h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HoverCard
        title="Alle Menschen sind frei und gleich an Würde und Rechten"
        subtitle="But in a much more real sense, I have no idea what I'm doing"
      />
      {/* <Header /> */}
    </div>
  );
}
