import Head from "next/head";
import Hero from "../components/Hero";
import Carousel from "../components/Carousel";

// The following import prevents a Font Awesome icon server-side rendering bug,
// where the icons flash from a very large icon down to a properly sized one:
import "@fortawesome/fontawesome-svg-core/styles.css";
// Prevent fontawesome from adding its CSS since we did it manually above:
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false; /* eslint-disable import/first */

export default function Home() {
  return (
    <div className="bg-black h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Grid /> */}
      <Hero />
      <Carousel />

      {/* <HoverCard
        title="Alle Menschen sind frei und gleich an Würde und Rechten"
        subtitle="But in a much more real sense, I have no idea what I'm doing"
      /> */}
    </div>
  );
}
