import Head from "next/head";
import Hero from "../components/Hero";
import Carousel from "../components/Carousel";

export default function Home() {
  return (
    <div className="bg-black h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Grid /> */}
      <Hero />
      <Carousel />

      {/* <HoverCard
        title="Alle Menschen sind frei und gleich an Würde und Rechten"
        subtitle="But in a much more real sense, I have no idea what I'm doing"
      /> */}
    </div>
  );
}
